# Generated by Django 2.2.6 on 2021-03-06 14:35

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210224_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[posts.validators.validator_not_empty]),
        ),
    ]
